# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}
ENV container=docker
ENV LC_ALL C

{% if item.environment.http_proxy is defined %}
RUN echo proxy={{ item.environment.http_proxy }} >> /etc/yum.conf
{% endif %}

# Start
RUN yum -y install epel-release && yum clean all

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/lib/systemd/systemd"]
